# Generated by Django 2.2 on 2019-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronunciation',
            name='phonetic_spelling',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
