# Generated by Django 2.2 on 2019-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
