# Generated by Django 2.2 on 2019-04-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0002_auto_20190413_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='pronunciation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='wordbuilder.Pronunciation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userword',
            name='pronunciation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='wordbuilder.Pronunciation'),
            preserve_default=False,
        ),
    ]
