# Generated by Django 2.2 on 2019-04-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0002_auto_20190414_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicalentry',
            name='pronunciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lexical_entries', to='wordbuilder.Pronunciation'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='pronunciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='wordbuilder.Pronunciation'),
        ),
    ]
