# Generated by Django 2.2 on 2019-04-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0002_auto_20190414_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userword',
            options={'ordering': ('-added',)},
        ),
    ]
