# Generated by Django 2.2 on 2019-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0003_auto_20190414_1835'),
        ('wordbuilder', '0003_auto_20190414_1252'),
    ]

    operations = [
    ]
