# Generated by Django 2.2 on 2019-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0005_auto_20190501_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='day_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='record_day_streak',
            field=models.IntegerField(default=0),
        ),
    ]
