# Generated by Django 2.2 on 2019-05-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0008_auto_20190509_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pkhbh2nage7k/public/'),
        ),
    ]
