# Generated by Django 2.2 on 2019-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbuilder', '0009_auto_20190511_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='r3yt8yrukj9h/public/'),
        ),
    ]
